### PR TITLE
feat(components): uniformize colors and variants

### PR DESCRIPTION
**Pull request by benjamincanac**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by TKDev7** [comment]
Is there a way to preview this change?

**Comment by benjamincanac** [comment]
@MrHBS I'd wait for this to be merged and then just run the playground 😊

**Comment by benjamincanac** [comment]
Here is a screenshot of the `Button` for example:
CleanShot 2024-07-08 at 11 42 33@2x

The `white` and `black` colors are removed in favor of the `gray` one which now have the exact same variants as colors.

**Comment by TKDev7** [comment]
Ah cool! I was hoping there was a netlify link or something lol

**Pull request merged**
